
const KEY="overflow-budget-v3";
const LEGACY=["overflow-budget-v1","overflow-budget-v2","overflow-budget-v2-1","overflow-budget-v2-2","overflow-budget-v2-3","overflow-budget-v2-4"];
const defaults={version:3,balances:{checking:0,savings:0,hysa:0,k401:0,roth:0,creditCard:800},checkingUpdatedAt:null,paycheck:{grossTakeHomeBeforeAllocations:1680,cadenceDays:14,nextDate:"2026-08-21"},payrollAllocations:{roth:100,hysa:100,k401:100,other:0},monthlyIncome:{amount:600,day:1},minimumBuffer:250,bufferGoal:1000,bills:[{id:"rent",name:"Rent",amount:1250,day:1,autopay:true},{id:"phone",name:"Phone",amount:117,day:15,autopay:true},{id:"electric",name:"Electric",amount:175,day:10,autopay:true},{id:"hulu",name:"Hulu",amount:27,day:27,autopay:true},{id:"renters",name:"Renter's insurance",amount:20,day:null,autopay:true},{id:"carinsurance",name:"Car insurance",amount:70,day:9,autopay:false},{id:"water",name:"Water",amount:50,day:1,autopay:false},{id:"internet",name:"Internet",amount:80,day:16,autopay:true}],paidBills:{},essentials:[{id:"groceries",name:"Groceries",monthlyTarget:500,cycleNeed:250,spentThisCycle:0,active:true},{id:"gas",name:"Gas",monthlyTarget:100,cycleNeed:50,spentThisCycle:0,active:true},{id:"eating",name:"Eating out",monthlyTarget:175,cycleNeed:0,spentThisCycle:0,active:false},{id:"household",name:"Household supplies",monthlyTarget:250,cycleNeed:0,spentThisCycle:0,active:false},{id:"pet",name:"Pet",monthlyTarget:150,cycleNeed:75,spentThisCycle:0,active:true}],oneTimeIncome:[],transactions:[],business:{cash:0,inventory:0,showReserve:500,realizedProfit:0}};
let data=load(), cursor=new Date(2026,7,1);
function clone(x){return JSON.parse(JSON.stringify(x))}
function migrate(r){let d=clone(defaults);Object.assign(d,r||{});d.balances={...defaults.balances,...(r?.balances||{})};d.business={...defaults.business,...(r?.business||{})};d.payrollAllocations={...defaults.payrollAllocations,...(r?.payrollAllocations||{})};d.paidBills=r?.paidBills||{};d.transactions=r?.transactions||[];if(r?.paycheck?.amount&&!r.paycheck.grossTakeHomeBeforeAllocations)d.paycheck.grossTakeHomeBeforeAllocations=r.paycheck.amount;if(Array.isArray(r?.essentials))d.essentials=r.essentials.map(x=>x.monthlyTarget!==undefined?x:{id:x.id,name:x.name,monthlyTarget:Number(x.amount||0),cycleNeed:["groceries","gas","pet"].includes(x.id)?({groceries:250,gas:50,pet:75}[x.id]):0,spentThisCycle:0,active:["groceries","gas","pet"].includes(x.id)});return d}
function load(){try{let v=localStorage.getItem(KEY);if(v)return migrate(JSON.parse(v));for(const k of LEGACY){v=localStorage.getItem(k);if(v){let d=migrate(JSON.parse(v));localStorage.setItem(KEY,JSON.stringify(d));return d}}}catch{}return clone(defaults)}
function save(){localStorage.setItem(KEY,JSON.stringify(data));render()}
const money=n=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(Number(n||0));
const parse=s=>{let [y,m,d]=s.split("-").map(Number);return new Date(y,m-1,d)}, iso=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`, add=(d,n)=>{let x=new Date(d);x.setDate(x.getDate()+n);return x}, start=d=>new Date(d.getFullYear(),d.getMonth(),d.getDate()), dim=(y,m)=>new Date(y,m+1,0).getDate(), clean=v=>Number(String(v||"").replace(/[$,\s]/g,"")||0);
function deposit(){let p=data.payrollAllocations;return Math.max(0,data.paycheck.grossTakeHomeBeforeAllocations-p.k401-p.roth-p.hysa-(p.other||0))}
function paydays(a,b){let d=parse(data.paycheck.nextDate);while(d<a)d=add(d,data.paycheck.cadenceDays);let o=[];while(d<=b){o.push(new Date(d));d=add(d,data.paycheck.cadenceDays)}return o}
function nextPay(){let t=start(new Date()),d=parse(data.paycheck.nextDate);while(d<t)d=add(d,data.paycheck.cadenceDays);return d}
function bkey(b,d){return `${b.id}:${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}`}
function paid(b,d){return !!data.paidBills[bkey(b,d)]}
function events(a,b){let o=[];for(const d of paydays(a,b))o.push({date:d,type:"income",name:"Paycheck",amount:deposit()});let c=new Date(a.getFullYear(),a.getMonth(),1);while(c<=b){let y=c.getFullYear(),m=c.getMonth(),mi=new Date(y,m,data.monthlyIncome.day);if(mi>=a&&mi<=b)o.push({date:mi,type:"income",name:"Monthly income",amount:data.monthlyIncome.amount});for(const x of data.bills){if(!x.day)continue;let bd=new Date(y,m,Math.min(x.day,dim(y,m))),p=paid(x,bd);if(bd>=a&&bd<=b)o.push({date:bd,type:"bill",name:x.name,amount:p?0:-x.amount,display:-x.amount,paid:p,billId:x.id})}c=new Date(y,m+1,1)}for(const x of data.oneTimeIncome){let d=parse(x.date);if(d>=a&&d<=b)o.push({date:d,type:"income",name:x.name,amount:x.amount})}return o.sort((x,y)=>x.date-y.date)}
function nextIncome(){let t=start(new Date()),c=[{date:nextPay(),name:"Paycheck",amount:deposit()}],m=new Date(t.getFullYear(),t.getMonth(),1);if(m<t)m=new Date(t.getFullYear(),t.getMonth()+1,1);c.push({date:m,name:"Monthly income",amount:data.monthlyIncome.amount});return c.sort((a,b)=>a.date-b.date)[0]}
function planned(){return data.essentials.reduce((s,x)=>s+(x.active?Math.max(0,x.cycleNeed-x.spentThisCycle):0),0)}
function billsBefore(d){return events(start(new Date()),d).filter(e=>e.type==="bill"&&!e.paid).reduce((s,e)=>s-e.amount,0)}
function safe(){let c=data.balances.checking;if(c<=0)return 0;let cut=nextIncome().date;return Math.max(0,c-billsBefore(cut)-planned()-data.minimumBuffer)}
function afterBills(){let end=add(nextPay(),-1);return data.balances.checking+events(start(new Date()),end).reduce((s,e)=>s+e.amount,0)-planned()}
function status(){let c=data.balances.checking;if(c<data.minimumBuffer)return["🔴 Recovery","#ff9d9d"];if(c<500)return["🟡 Stable","#ffd986"];if(c<1000)return["🟢 Healthy","#9ce0b8"];return["⭐ Strong","#d9b861"]}
function jobs(){let c=data.balances.checking,b=billsBefore(nextIncome().date),p=planned(),buf=Math.min(Math.max(c-b-p,0),data.minimumBuffer),free=Math.max(0,c-b-p-data.minimumBuffer);return{b,p,buf,free}}
function show(html){document.querySelector("#modalBody").innerHTML=html;document.querySelector("#modal").showModal()}
function actions(txt="Save"){return `<div class="modalactions"><button value="cancel" class="secondary">Cancel</button><button id="modalSave" value="default" class="primary">${txt}</button></div>`}
function addTx(name,amt,note=""){data.transactions.unshift({id:Date.now(),date:iso(new Date()),name,amount:amt,note})}
function render(){
 let st=status();document.querySelector("#status").textContent=st[0];document.querySelector("#status").style.color=st[1];document.querySelector("#checking").textContent=money(data.balances.checking);document.querySelector("#safe").textContent=money(safe());let ni=nextIncome();document.querySelector("#nextMoney").textContent=money(ni.amount);document.querySelector("#nextMoneyDate").textContent=`${ni.name} • ${ni.date.toLocaleDateString("en-US",{month:"short",day:"numeric"})}`;document.querySelector("#afterBills").textContent=money(afterBills());document.querySelector("#bufferNow").textContent=money(data.minimumBuffer);document.querySelector("#bufferGoal").textContent=money(data.bufferGoal);document.querySelector("#bufferBar").style.width=`${Math.min(100,data.minimumBuffer/data.bufferGoal*100)}%`;
 let ms=[500,750,1000].filter(x=>x>data.minimumBuffer);document.querySelector("#bufferNext").textContent=ms.length?`Next milestone: ${money(ms[0])}`:"Goal reached";
 let now=new Date(),y=now.getFullYear(),m=now.getMonth(),tot=0,pd=0,rows=[];for(const b of data.bills){if(!b.day)continue;let d=new Date(y,m,Math.min(b.day,dim(y,m)));tot+=b.amount;if(paid(b,d))pd+=b.amount;rows.push({b,d,p:paid(b,d)})}rows.sort((a,b)=>a.d-b.d);document.querySelector("#billTotal").textContent=money(tot);document.querySelector("#billPaid").textContent=money(pd);document.querySelector("#billRemain").textContent=money(tot-pd);document.querySelector("#billList").innerHTML=rows.map(x=>`<div class="check ${x.p?"paid":""}"><button class="checkbtn" onclick="toggleBill('${x.b.id}','${iso(x.d)}')">${x.p?"✓":""}</button><div><strong>${x.b.name}</strong><div class="meta">${x.d.toLocaleDateString("en-US",{month:"short",day:"numeric"})} • ${money(x.b.amount)} • ${x.b.autopay?"autopay":"manual"}</div></div><div class="right">${x.p?"Paid":"Due"}</div></div>`).join("");
 document.querySelector("#monthName").textContent=cursor.toLocaleDateString("en-US",{month:"long",year:"numeric"});let first=new Date(cursor.getFullYear(),cursor.getMonth(),1),cs=new Date(first.getFullYear(),first.getMonth(),1-first.getDay()),ce=add(cs,41),ev=events(cs,ce),cells="";for(let i=0;i<42;i++){let d=add(cs,i),de=ev.filter(e=>e.date.toDateString()===d.toDateString());cells+=`<button class="day ${d.getMonth()!==cursor.getMonth()?"other":""} ${d.toDateString()===new Date().toDateString()?"today":""}"><strong>${d.getDate()}</strong><div class="dots">${de.slice(0,4).map(e=>`<i class="${e.paid?"paid":e.type}"></i>`).join("")}</div></button>`}document.querySelector("#calendarGrid").innerHTML=cells;document.querySelector("#coming").innerHTML=events(start(new Date()),add(start(new Date()),30)).slice(0,12).map(e=>`<div class="event"><i class="${e.paid?"income":e.type}"></i><div><strong>${e.name}</strong><div class="meta">${e.date.toLocaleDateString("en-US",{month:"short",day:"numeric"})}${e.paid?" • Paid":""}</div></div><div class="amt">${e.paid?"Paid":money(e.display??e.amount)}</div></div>`).join("");
 let j=jobs();document.querySelector("#jobBills").textContent=money(j.b);document.querySelector("#jobSpend").textContent=money(j.p);document.querySelector("#jobBuffer").textContent=money(j.buf);document.querySelector("#jobFree").textContent=money(j.free);let pp=nextPay(),pend=add(pp,13),pev=events(pp,pend),pb=pev.filter(e=>e.type==="bill"&&!e.paid).reduce((s,e)=>s-e.amount,0),oi=pev.filter(e=>e.type==="income"&&e.name!=="Paycheck").reduce((s,e)=>s+e.amount,0),proj=data.balances.checking+deposit()+oi-pb-planned(),free=Math.max(0,proj-data.minimumBuffer);document.querySelector("#payPlan").innerHTML=[["Checking now",money(data.balances.checking)],["Paycheck deposit","+"+money(deposit())],["Other income","+"+money(oi)],["Bills","−"+money(pb)],["Planned spending","−"+money(planned())],["Projected",money(proj)],["Remaining",money(free)]].map((x,i)=>`<div><span>${x[0]}</span><strong>${x[1]}</strong></div>`).join("");
 document.querySelector("#plannedList").innerHTML=data.essentials.map((x,i)=>{let rem=x.active?Math.max(0,x.cycleNeed-x.spentThisCycle):0;return `<div class="planned"><div class="row"><strong>${x.name}</strong><button class="link" onclick="editEssential(${i})">Edit</button></div><div class="meta">${x.active?`${money(x.spentThisCycle)} spent • ${money(rem)} left`:"Not funded this cycle"}</div></div>`}).join("");
 document.querySelector("#accounts").innerHTML=[["Checking",data.balances.checking],["Savings",data.balances.savings],["HYSA",data.balances.hysa],["401(k)",data.balances.k401],["Roth IRA",data.balances.roth],["Credit card",-data.balances.creditCard]].map(x=>`<div><span>${x[0]}</span><strong>${money(x[1])}</strong></div>`).join("");
 document.querySelector("#goals").innerHTML=`<div class="goalitem"><div class="row"><strong>Checking buffer</strong><span>${money(data.minimumBuffer)} / ${money(data.bufferGoal)}</span></div></div><div class="goalitem"><div class="row"><strong>Credit card</strong><span>${money(data.balances.creditCard)} left</span></div></div>`;
 document.querySelector("#history").innerHTML=data.transactions.slice(0,12).map(t=>`<div class="event"><i class="${t.amount>=0?"income":""}"></i><div><strong>${t.name}</strong><div class="meta">${t.date}${t.note?" • "+t.note:""}</div></div><div class="amt">${t.amount>=0?"+":""}${money(t.amount)}</div></div>`).join("")||`<div class="muted">No transactions yet.</div>`;
 let b=data.business;document.querySelector("#bizValue").textContent=money(b.cash+b.inventory);document.querySelector("#bizCards").innerHTML=[["Cash",b.cash],["Inventory",b.inventory],["Show reserve",b.showReserve],["Realized profit",b.realizedProfit]].map(x=>`<div><span>${x[0]}</span><strong>${money(x[1])}</strong></div>`).join("");
}
window.toggleBill=(id,ds)=>{let b=data.bills.find(x=>x.id===id),d=parse(ds),k=bkey(b,d);if(paid(b,d))delete data.paidBills[k];else{data.paidBills[k]={paid:true,paidAt:new Date().toISOString()};addTx(b.name,-b.amount,"Marked paid")}save()};
window.editEssential=i=>{let x=data.essentials[i];show(`<div class="modalstack"><h2>${x.name}</h2><label>Monthly target<input id="em" class="modalinput" value="${x.monthlyTarget}"></label><label>Needed this cycle<input id="ec" class="modalinput" value="${x.cycleNeed}"></label><label>Spent this cycle<input id="es" class="modalinput" value="${x.spentThisCycle}"></label><label><input id="ea" type="checkbox" ${x.active?"checked":""}> Fund this cycle</label></div>${actions()}`);document.querySelector("#modalSave").onclick=()=>{x.monthlyTarget=clean(em.value);x.cycleNeed=clean(ec.value);x.spentThisCycle=clean(es.value);x.active=ea.checked;save()}};
function editBalances(){show(`<div class="modalstack"><h2>Update balances</h2>${Object.entries({checking:"Checking",savings:"Savings",hysa:"HYSA",k401:"401(k)",roth:"Roth IRA",creditCard:"Credit card"}).map(([k,l])=>`<label>${l}<input id="b_${k}" class="modalinput" type="text" value="${data.balances[k]}"></label>`).join("")}</div>${actions()}`);document.querySelector("#modalSave").onclick=()=>{Object.keys(data.balances).forEach(k=>data.balances[k]=clean(document.querySelector("#b_"+k).value));data.checkingUpdatedAt=new Date().toISOString();save()}}
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{let id=b.dataset.tab;document.querySelectorAll(".view").forEach(v=>v.classList.toggle("active",v.id===id));document.querySelectorAll(".tab").forEach(t=>t.classList.toggle("active",t===b));title.textContent={home:"Home",bills:"Bills",calendar:"Calendar",allocate:"Allocate",eclipse:"Eclipse"}[id];scrollTo(0,0)});
checking.onclick=editChecking.onclick=editBalances.onclick=editBalances;
safe.onclick=()=>show(`<div class="modalstack"><h2>Safe to spend</h2><div class="lines"><div><span>Checking</span><strong>${money(data.balances.checking)}</strong></div><div><span>Bills before next income</span><strong>−${money(billsBefore(nextIncome().date))}</strong></div><div><span>Planned spending</span><strong>−${money(planned())}</strong></div><div><span>Buffer</span><strong>−${money(data.minimumBuffer)}</strong></div><div><span>Safe today</span><strong>${money(safe())}</strong></div></div></div>${actions("Close")}`);
quickCheck.onclick=()=>{let a=clean(quickAmount.value),s=safe();quickResult.className="result";quickResult.innerHTML=!a?"Enter an amount first.":a<=s?`✓ Yes. ${money(s-a)} safe remains.`:`Not yet. You're ${money(a-s)} above today's safe amount.`};
editBuffer.onclick=()=>{show(`<div class="modalstack"><h2>Edit buffer</h2><label>Protected floor<input id="bf" class="modalinput" value="${data.minimumBuffer}"></label><label>Goal<input id="bg" class="modalinput" value="${data.bufferGoal}"></label></div>${actions()}`);modalSave.onclick=()=>{data.minimumBuffer=clean(bf.value);data.bufferGoal=clean(bg.value);save()}};
prev.onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()-1,1);render()};next.onclick=()=>{cursor=new Date(cursor.getFullYear(),cursor.getMonth()+1,1);render()};
editPayroll.onclick=()=>{let p=data.payrollAllocations;show(`<div class="modalstack"><h2>Edit payroll</h2><label>Pay before allocations<input id="pg" class="modalinput" value="${data.paycheck.grossTakeHomeBeforeAllocations}"></label><label>401(k)<input id="p4" class="modalinput" value="${p.k401}"></label><label>Roth IRA<input id="pr" class="modalinput" value="${p.roth}"></label><label>HYSA<input id="ph" class="modalinput" value="${p.hysa}"></label><label>Other<input id="po" class="modalinput" value="${p.other}"></label><label>Next payday<input id="pd" class="modalinput" type="date" value="${data.paycheck.nextDate}"></label></div>${actions()}`);modalSave.onclick=()=>{data.paycheck.grossTakeHomeBeforeAllocations=clean(pg.value);p.k401=clean(p4.value);p.roth=clean(pr.value);p.hysa=clean(ph.value);p.other=clean(po.value);data.paycheck.nextDate=pd.value;save()}};
resetCycle.onclick=()=>{if(confirm("Reset spent amounts for a new pay cycle?")){data.essentials.forEach(x=>x.spentThisCycle=0);save()}};
whyJobs.onclick=()=>show(`<div class="modalstack"><h2>Money jobs</h2><p>Checking is divided into upcoming bills, planned spending, your protected buffer, and money that is truly free.</p></div>${actions("Close")}`);
function addEntry(){show(`<div class="modalstack"><h2>Add spending</h2><label>Category<select id="ac" class="modalselect">${data.essentials.map(x=>`<option value="${x.id}">${x.name}</option>`).join("")}</select></label><label>Amount<input id="aa" class="modalinput" inputmode="decimal"></label><label>Note<input id="an" class="modalinput"></label></div>${actions("Add")}`);modalSave.onclick=()=>{let x=data.essentials.find(e=>e.id===ac.value),a=clean(aa.value);x.spentThisCycle+=a;addTx(x.name,-a,an.value);save()}}
addBtn.onclick=addSpend.onclick=addEntry;
backup.onclick=()=>{let blob=new Blob([JSON.stringify(data,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`overflow-backup-${iso(new Date())}.json`;a.click()};
restore.onclick=()=>restoreFile.click();restoreFile.onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{data=migrate(JSON.parse(r.result));save();alert("Backup imported.")}catch{alert("Could not import backup.")}};r.readAsText(f)};
market.oninput=pct.oninput=()=>{let m=clean(market.value),p=clean(pct.value);offer.innerHTML=m?`Max offer at ${p}%: <strong>${money(m*p/100)}</strong>`:"Enter market value to calculate a max offer."};
editBiz.onclick=()=>{let b=data.business;show(`<div class="modalstack"><h2>Eclipse balances</h2><label>Cash<input id="bc" class="modalinput" value="${b.cash}"></label><label>Inventory<input id="bi" class="modalinput" value="${b.inventory}"></label><label>Show reserve<input id="br" class="modalinput" value="${b.showReserve}"></label></div>${actions()}`);modalSave.onclick=()=>{b.cash=clean(bc.value);b.inventory=clean(bi.value);b.showReserve=clean(br.value);save()}};
recordSale.onclick=()=>{let s=clean(sale.value),c=clean(cost.value),b=data.business;if(!s)return;b.cash+=s;b.inventory=Math.max(0,b.inventory-c);b.realizedProfit+=s-c;saleResult.textContent=`Recorded ${money(s-c)} realized profit.`;save()};
newBill.onclick=()=>{show(`<div class="modalstack"><h2>Add bill</h2><label>Name<input id="bn" class="modalinput"></label><label>Amount<input id="ba" class="modalinput"></label><label>Due day<input id="bd" class="modalinput"></label><label><input id="bo" type="checkbox"> Autopay</label></div>${actions("Add")}`);modalSave.onclick=()=>{data.bills.push({id:Date.now().toString(),name:bn.value||"Bill",amount:clean(ba.value),day:Number(bd.value)||null,autopay:bo.checked});save()}};
editGoals.onclick=()=>editBuffer.click();
if("serviceWorker"in navigator)navigator.serviceWorker.register("sw.js?v=3.0",{updateViaCache:"none"}).then(r=>r.update()).catch(()=>{});
render();
